/**
 * Lo-fi audio engine — procedural Web Audio API synthesis.
 * ⚠️  DO NOT edit this file to change tracks.
 *     Edit src/config/lofiTracks.ts instead.
 */

import { LOFI_TRACK_CONFIGS, type LofiTrackConfig, type TrackBar } from '../config/lofiTracks';

// Re-export so Settings/other UI can import track metadata from one place
export type { LofiTrackConfig as LofiTrack };
export const LOFI_TRACKS = LOFI_TRACK_CONFIGS;

function mf(midi: number): number {
  return 440 * 2 ** ((midi - 69) / 12);
}

// ── Engine ────────────────────────────────────────────────────────────────────
class LofiEngine {
  private actx: AudioContext | null = null;
  private masterGain: GainNode | null = null;
  private playing = false;
  private trackIdx = 0;
  private barIdx = 0;
  private nextBarTime = 0;
  private scheduleTimer: ReturnType<typeof setTimeout> | null = null;
  private noiseBuffer: AudioBuffer | null = null;

  // Rain track persistent nodes
  private rainSource: AudioBufferSourceNode | null = null;

  // ── Boot ──────────────────────────────────────────────────────────────────
  private boot(): AudioContext {
    if (!this.actx) {
      const AC = window.AudioContext ||
        (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
      this.actx = new AC();

      this.masterGain = this.actx.createGain();
      const comp = this.actx.createDynamicsCompressor();
      comp.threshold.value = -14; comp.knee.value = 8;
      comp.ratio.value = 4;       comp.attack.value = 0.004; comp.release.value = 0.28;
      this.masterGain.connect(comp);
      comp.connect(this.actx.destination);

      // 3-second white-noise buffer (reused for all percussive + rain sounds)
      const sr = this.actx.sampleRate;
      this.noiseBuffer = this.actx.createBuffer(1, sr * 3, sr);
      const data = this.noiseBuffer.getChannelData(0);
      for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
    }
    if (this.actx.state === 'suspended') this.actx.resume();
    return this.actx;
  }

  // ── Pad variants ──────────────────────────────────────────────────────────

  /**
   * Generic pad — 2 slightly-detuned oscillators through a LPF.
   * @param oscType  — changes the harmonic character entirely
   * @param lpfFreq  — how open/dark the tone is
   * @param attack   — how slowly it swells in
   * @param volPerNote — amplitude per chord note
   * @param detuneCents — chorus width in cents
   */
  private playPad(
    chordMidi: number[],
    startTime: number,
    duration: number,
    oscType: OscillatorType,
    lpfFreq: number,
    attack: number,
    volPerNote: number,
    detuneCents = 8,
  ) {
    const c = this.actx!;
    const mg = this.masterGain!;
    const release = Math.min(duration * 0.28, 0.6);
    const detune = 2 ** (detuneCents / 1200);

    for (const midi of chordMidi) {
      const freq = mf(midi);
      const osc1 = c.createOscillator();
      const osc2 = c.createOscillator();
      const gain = c.createGain();
      const lpf  = c.createBiquadFilter();

      osc1.type = oscType;  osc1.frequency.value = freq;
      osc2.type = oscType;  osc2.frequency.value = freq * detune;
      lpf.type  = 'lowpass'; lpf.frequency.value = lpfFreq; lpf.Q.value = 0.6;

      gain.gain.setValueAtTime(0, startTime);
      gain.gain.linearRampToValueAtTime(volPerNote, startTime + attack);
      gain.gain.setValueAtTime(volPerNote, startTime + duration - release);
      gain.gain.linearRampToValueAtTime(0, startTime + duration + 0.05);

      osc1.connect(gain); osc2.connect(gain);
      gain.connect(lpf);  lpf.connect(mg);
      osc1.start(startTime); osc1.stop(startTime + duration + 0.15);
      osc2.start(startTime); osc2.stop(startTime + duration + 0.15);
    }
  }

  // ── Bass variants ─────────────────────────────────────────────────────────

  private playBass(
    midi: number,
    startTime: number,
    noteDur: number,
    vol = 0.22,
    lpfFreq = 280,
    oscType: OscillatorType = 'sine',
  ) {
    const c = this.actx!;
    const osc  = c.createOscillator();
    const gain = c.createGain();
    const lpf  = c.createBiquadFilter();

    osc.type = oscType; osc.frequency.value = mf(midi);
    lpf.type = 'lowpass'; lpf.frequency.value = lpfFreq;

    gain.gain.setValueAtTime(0, startTime);
    gain.gain.linearRampToValueAtTime(vol, startTime + 0.016);
    gain.gain.exponentialRampToValueAtTime(vol * 0.32, startTime + noteDur * 0.44);
    gain.gain.exponentialRampToValueAtTime(0.001, startTime + noteDur * 0.85);

    osc.connect(gain); gain.connect(lpf); lpf.connect(this.masterGain!);
    osc.start(startTime); osc.stop(startTime + noteDur);
  }

  // ── Drum variants ─────────────────────────────────────────────────────────

  /** Standard boom-bap kick — sine pitch drop */
  private playKick(t: number, vol = 0.70) {
    const c = this.actx!;
    const osc  = c.createOscillator();
    const gain = c.createGain();
    osc.type = 'sine';
    osc.frequency.setValueAtTime(110, t);
    osc.frequency.exponentialRampToValueAtTime(38, t + 0.075);
    gain.gain.setValueAtTime(vol, t + 0.001);
    gain.gain.exponentialRampToValueAtTime(0.001, t + 0.22);
    osc.connect(gain); gain.connect(this.masterGain!);
    osc.start(t); osc.stop(t + 0.26);
  }

  /** Heavy 808-style kick — deeper sub, longer decay */
  private playKick808(t: number) {
    const c = this.actx!;
    const osc  = c.createOscillator();
    const gain = c.createGain();
    osc.type = 'sine';
    osc.frequency.setValueAtTime(140, t);
    osc.frequency.exponentialRampToValueAtTime(42, t + 0.11);
    gain.gain.setValueAtTime(0.88, t + 0.001);
    gain.gain.exponentialRampToValueAtTime(0.001, t + 0.38);
    osc.connect(gain); gain.connect(this.masterGain!);
    osc.start(t); osc.stop(t + 0.42);
  }

  /** Standard snare — noise burst + sine tone body */
  private playSnare(t: number, vol = 0.22) {
    if (!this.noiseBuffer) return;
    const c = this.actx!;
    const mg = this.masterGain!;

    const src   = c.createBufferSource();
    const bpf   = c.createBiquadFilter();
    const nGain = c.createGain();
    src.buffer = this.noiseBuffer;
    bpf.type = 'bandpass'; bpf.frequency.value = 1600; bpf.Q.value = 0.55;
    nGain.gain.setValueAtTime(vol, t);
    nGain.gain.exponentialRampToValueAtTime(0.001, t + 0.17);
    src.connect(bpf); bpf.connect(nGain); nGain.connect(mg);
    src.start(t); src.stop(t + 0.20);

    const osc   = c.createOscillator();
    const oGain = c.createGain();
    osc.type = 'sine'; osc.frequency.value = 185;
    oGain.gain.setValueAtTime(vol * 0.45, t);
    oGain.gain.exponentialRampToValueAtTime(0.001, t + 0.07);
    osc.connect(oGain); oGain.connect(mg);
    osc.start(t); osc.stop(t + 0.10);
  }

  /** Brush snare — soft noise only, no tone, very quiet */
  private playBrushSnare(t: number) {
    if (!this.noiseBuffer) return;
    const c = this.actx!;
    const src   = c.createBufferSource();
    const bpf   = c.createBiquadFilter();
    const nGain = c.createGain();
    src.buffer = this.noiseBuffer;
    bpf.type = 'bandpass'; bpf.frequency.value = 2800; bpf.Q.value = 0.4;
    nGain.gain.setValueAtTime(0.07, t);
    nGain.gain.exponentialRampToValueAtTime(0.001, t + 0.24);
    src.connect(bpf); bpf.connect(nGain); nGain.connect(this.masterGain!);
    src.start(t); src.stop(t + 0.28);
  }

  /** Ghost snare — very quiet noise for jazz ghost notes */
  private playGhost(t: number) {
    if (!this.noiseBuffer) return;
    const c = this.actx!;
    const src   = c.createBufferSource();
    const bpf   = c.createBiquadFilter();
    const nGain = c.createGain();
    src.buffer = this.noiseBuffer;
    bpf.type = 'bandpass'; bpf.frequency.value = 1400; bpf.Q.value = 0.6;
    nGain.gain.setValueAtTime(0.055, t);
    nGain.gain.exponentialRampToValueAtTime(0.001, t + 0.09);
    src.connect(bpf); bpf.connect(nGain); nGain.connect(this.masterGain!);
    src.start(t); src.stop(t + 0.12);
  }

  /** Closed hi-hat */
  private playHH(t: number, vol = 0.08) {
    if (!this.noiseBuffer) return;
    const c   = this.actx!;
    const src = c.createBufferSource();
    const hpf = c.createBiquadFilter();
    const gain = c.createGain();
    src.buffer = this.noiseBuffer;
    hpf.type = 'highpass'; hpf.frequency.value = 7400;
    gain.gain.setValueAtTime(vol, t + 0.001);
    gain.gain.exponentialRampToValueAtTime(0.001, t + 0.045);
    src.connect(hpf); hpf.connect(gain); gain.connect(this.masterGain!);
    src.start(t); src.stop(t + 0.06);
  }

  /** Open hi-hat */
  private playOpenHH(t: number, vol = 0.10) {
    if (!this.noiseBuffer) return;
    const c   = this.actx!;
    const src = c.createBufferSource();
    const hpf = c.createBiquadFilter();
    const gain = c.createGain();
    src.buffer = this.noiseBuffer;
    hpf.type = 'highpass'; hpf.frequency.value = 6800;
    gain.gain.setValueAtTime(vol, t + 0.001);
    gain.gain.exponentialRampToValueAtTime(0.001, t + 0.20);
    src.connect(hpf); hpf.connect(gain); gain.connect(this.masterGain!);
    src.start(t); src.stop(t + 0.22);
  }

  // ── Rain texture ──────────────────────────────────────────────────────────

  private startRain() {
    if (!this.noiseBuffer || !this.actx) return;
    this.stopRain();

    // Layer 1: high-frequency hiss (distant rain)
    const src1  = this.actx.createBufferSource();
    const hpf1  = this.actx.createBiquadFilter();
    const gain1 = this.actx.createGain();
    src1.buffer = this.noiseBuffer; src1.loop = true;
    hpf1.type = 'highpass'; hpf1.frequency.value = 5500;
    gain1.gain.value = 0.055;
    src1.connect(hpf1); hpf1.connect(gain1); gain1.connect(this.masterGain!);
    src1.start();

    // Layer 2: low-mid rumble (nearby rainfall)
    const src2  = this.actx.createBufferSource();
    const bpf2  = this.actx.createBiquadFilter();
    const gain2 = this.actx.createGain();
    src2.buffer = this.noiseBuffer; src2.loop = true;
    bpf2.type = 'bandpass'; bpf2.frequency.value = 900; bpf2.Q.value = 0.3;
    gain2.gain.value = 0.028;
    src2.connect(bpf2); bpf2.connect(gain2); gain2.connect(this.masterGain!);
    src2.start();

    this.rainSource = src1;
    this._rainSrc2  = src2;
  }

  private _rainSrc2: AudioBufferSourceNode | null = null;

  private stopRain() {
    for (const src of [this.rainSource, this._rainSrc2]) {
      if (src) { try { src.stop(); } catch { /* already stopped */ } }
    }
    this.rainSource = null;
    this._rainSrc2 = null;
  }

  // ── Per-track bar schedulers ───────────────────────────────────────────────

  /** Track 0 — LATE NIGHT
   *  Dark triangle pads, half-time drums (kick on 1+3, snare on 3 only),
   *  sparse quarter-note hats, bass on beats 1 & 3 only, sub bass layer.
   */
  private scheduleBar0(bar: TrackBar, barStart: number, beatDur: number) {
    const barDur  = beatDur * 4;
    const stepDur = beatDur / 4;

    // Pad: triangle, very dark LPF (520 Hz), slow swell
    this.playPad(bar.chord, barStart, barDur, 'triangle', 520, 0.52, 0.048, 6);

    // Sub bass: one octave below root, very low LPF
    this.playBass(bar.bass - 12, barStart, beatDur * 2, 0.14, 140, 'sine');

    // Bass pattern: steps 0 and 8 (beats 1 and 3)
    const bassSteps = [1,0,0,0, 0,0,0,0, 1,0,0,0, 0,0,0,0];
    bassSteps.forEach((on, step) => {
      if (!on) return;
      const h = (Math.random() - 0.5) * 0.007;
      this.playBass(bar.bass, barStart + step * stepDur + h, beatDur, 0.21, 260, 'sine');
    });

    // Drums: half-time — kick 1+3, snare beat 3 only, quarter hats (very sparse)
    const kick  = [1,0,0,0, 0,0,0,0, 1,0,0,0, 0,0,0,0];
    const snare = [0,0,0,0, 0,0,0,0, 1,0,0,0, 0,0,0,0];  // snare on beat 3 only
    const hhCl  = [1,0,0,0, 1,0,0,0, 1,0,0,0, 1,0,0,0];  // quarter notes

    for (let s = 0; s < 16; s++) {
      const t = barStart + s * stepDur + (Math.random() - 0.5) * 0.005;
      if (kick[s])  this.playKick(t, 0.62);
      if (snare[s]) this.playSnare(t, 0.18);
      if (hhCl[s])  this.playHH(t, 0.055);
    }
  }

  /** Track 1 — COFFEE SHOP
   *  Bright open sine pads (LPF 1500 Hz), active 8th-note hats with open hat
   *  on the "and" of 2 and 4, syncopated bass, short pluck melody layer.
   */
  private scheduleBar1(bar: TrackBar, barStart: number, beatDur: number) {
    const barDur  = beatDur * 4;
    const stepDur = beatDur / 4;

    // Pad: sine, wide-open filter (1500 Hz), medium attack — bright and airy
    this.playPad(bar.chord, barStart, barDur, 'sine', 1500, 0.22, 0.052, 12);

    // Bass: syncopated — beat 1, "2-and" (step 5), beat 3, "4-and" (step 13)
    [0, 5, 8, 13].forEach(step => {
      const h = (Math.random() - 0.5) * 0.005;
      const noteDur = step === 5 || step === 13 ? beatDur * 0.6 : beatDur;
      this.playBass(bar.bass, barStart + step * stepDur + h, noteDur, 0.19, 320, 'triangle');
    });

    // Drums: 8th-note hats, open hat before beats 2 and 4, standard kick+snare
    const kick  = [1,0,0,0, 0,0,0,0, 1,0,0,0, 0,0,0,0];
    const snare = [0,0,0,0, 1,0,0,0, 0,0,0,0, 1,0,0,0];
    const hhCl  = [1,0,1,0, 0,0,1,0, 1,0,1,0, 0,0,1,0];  // 8th notes, skip before open
    const hhOp  = [0,0,0,0, 1,0,0,0, 0,0,0,0, 1,0,0,0];  // open on "2" and "4"

    for (let s = 0; s < 16; s++) {
      const t = barStart + s * stepDur + (Math.random() - 0.5) * 0.004;
      if (kick[s])       this.playKick(t, 0.65);
      if (snare[s])      this.playSnare(t, 0.20);
      if (hhOp[s])       this.playOpenHH(t, 0.10);
      else if (hhCl[s])  this.playHH(t, 0.09);
    }

    // Pluck melody: 2-3 high notes from the chord, one octave up
    // Place them at steps 2, 6, 10 (off-beat 16ths) for a light melodic hook
    const melodySteps = [2, 6, 10];
    const topNotes = bar.chord.slice(-3); // top 3 chord notes
    melodySteps.forEach((step, i) => {
      const midi = topNotes[i % topNotes.length] + 12; // one octave up
      const t = barStart + step * stepDur + (Math.random() - 0.5) * 0.003;
      const c = this.actx!;
      const osc  = c.createOscillator();
      const gain = c.createGain();
      const lpf  = c.createBiquadFilter();
      osc.type = 'triangle'; osc.frequency.value = mf(midi);
      lpf.type = 'lowpass'; lpf.frequency.value = 3200;
      gain.gain.setValueAtTime(0, t);
      gain.gain.linearRampToValueAtTime(0.065, t + 0.009);
      gain.gain.exponentialRampToValueAtTime(0.001, t + 0.18);
      osc.connect(gain); gain.connect(lpf); lpf.connect(this.masterGain!);
      osc.start(t); osc.stop(t + 0.22);
    });
  }

  /** Track 2 — RAINY WINDOW
   *  Ultra-dark sine pads (LPF 360 Hz, very slow swell), two-layer rain texture,
   *  bass on beat 1 only, brush snare on 2+4, no kick, no hi-hats.
   */
  private scheduleBar2(bar: TrackBar, barStart: number, beatDur: number) {
    const barDur  = beatDur * 4;
    const stepDur = beatDur / 4;

    // Pad: sine, very dark (360 Hz LPF), very slow attack — almost ambient
    this.playPad(bar.chord, barStart, barDur, 'sine', 360, 0.95, 0.042, 5);

    // Bass: root on beat 1 only, long sustain, sub-frequency
    this.playBass(bar.bass, barStart, beatDur * 2.2, 0.16, 200, 'sine');

    // Drums: brush snare on beats 2 and 4 only — everything else silent
    const snare = [0,0,0,0, 1,0,0,0, 0,0,0,0, 1,0,0,0];
    for (let s = 0; s < 16; s++) {
      const t = barStart + s * stepDur + (Math.random() - 0.5) * 0.012; // more humanise
      if (snare[s]) this.playBrushSnare(t);
    }
    // Rain is started/stopped in play()/stop() — not per-bar
  }

  /** Track 3 — GOLDEN HOUR
   *  Warm sawtooth pads through LPF (Rhodes-like), jazz-influenced drums
   *  (ghost notes, complex hi-hats), syncopated bass, bright chord stabs on
   *  beats 2 and 4 as rhythmic punctuation.
   */
  private scheduleBar3(bar: TrackBar, barStart: number, beatDur: number) {
    const barDur  = beatDur * 4;
    const stepDur = beatDur / 4;

    // Pad: sawtooth through 700 Hz LPF — warm and harmonically rich
    this.playPad(bar.chord, barStart, barDur, 'sawtooth', 700, 0.34, 0.032, 4);

    // Bass: off-beat jazz feel — steps 0, 6, 8, 14
    [0, 6, 8, 14].forEach(step => {
      const h = (Math.random() - 0.5) * 0.006;
      this.playBass(bar.bass, barStart + step * stepDur + h, beatDur * 0.7, 0.20, 300, 'sine');
    });

    // Drums: jazz feel — kick on 1 and "2 and", snare 2+4, ghost on 3-and, complex hats
    const kick  = [1,0,0,0, 0,1,0,0, 0,0,0,0, 0,0,0,0];  // 1, "2 and"
    const snare = [0,0,0,0, 1,0,0,0, 0,0,0,0, 1,0,0,0];  // beats 2, 4
    const ghost = [0,0,0,0, 0,0,0,0, 0,0,1,0, 0,0,0,1];  // ghost on "3 and", "4 and"
    // Irregular jazz hi-hat pattern (swing feel)
    const hhCl  = [1,0,1,0, 0,1,0,0, 1,0,1,0, 0,1,0,0];
    const hhOp  = [0,0,0,0, 0,0,1,0, 0,0,0,0, 0,0,1,0];

    for (let s = 0; s < 16; s++) {
      const t = barStart + s * stepDur + (Math.random() - 0.5) * 0.006;
      if (kick[s])       this.playKick(t, 0.58);
      if (snare[s])      this.playSnare(t, 0.19);
      if (ghost[s])      this.playGhost(t);
      if (hhOp[s])       this.playOpenHH(t, 0.08);
      else if (hhCl[s])  this.playHH(t, 0.07);
    }

    // Chord stabs on beats 2 and 4 — fast attack, quick release, brighter filter
    // Gives a rhythm-guitar "chick" punctuation effect
    [4, 12].forEach(step => {
      const t = barStart + step * stepDur + (Math.random() - 0.5) * 0.004;
      const c = this.actx!;
      for (const midi of bar.chord) {
        const osc  = c.createOscillator();
        const gain = c.createGain();
        const lpf  = c.createBiquadFilter();
        osc.type = 'sawtooth'; osc.frequency.value = mf(midi);
        lpf.type = 'lowpass'; lpf.frequency.value = 2200;
        gain.gain.setValueAtTime(0, t);
        gain.gain.linearRampToValueAtTime(0.028, t + 0.008);
        gain.gain.exponentialRampToValueAtTime(0.001, t + 0.18);
        osc.connect(gain); gain.connect(lpf); lpf.connect(this.masterGain!);
        osc.start(t); osc.stop(t + 0.22);
      }
    });
  }

  /** Track 4 — MIDNIGHT DRIVE
   *  Square pads through heavy LPF (intense/gritty), heavy 808-style kicks,
   *  rapid 16th-note hi-hats, driving bass on every beat + extra hits,
   *  upward chord arpeggio at bar start.
   */
  private scheduleBar4(bar: TrackBar, barStart: number, beatDur: number) {
    const barDur  = beatDur * 4;
    const stepDur = beatDur / 4;

    // Pad: square, very heavy LPF (580 Hz) — thick and gritty
    this.playPad(bar.chord, barStart, barDur, 'square', 580, 0.20, 0.030, 3);

    // Bass: driving — steps 0, 2, 4, 8, 10, 12 (frequent, energetic)
    [0, 2, 4, 8, 10, 12].forEach(step => {
      const h = (Math.random() - 0.5) * 0.004;
      const noteDur = stepDur * 1.8;
      this.playBass(bar.bass, barStart + step * stepDur + h, noteDur, 0.26, 240, 'sine');
    });

    // Drums: heavy trap/hip-hop — 808 kick, heavy snare, all 16th hats
    const kick  = [1,0,0,1, 0,0,0,0, 1,0,0,1, 0,0,0,0];  // 808 pattern
    const snare = [0,0,0,0, 1,0,0,0, 0,0,0,0, 1,0,0,1];  // 2, 4, "4 and"
    const hhCl  = [1,1,1,1, 1,1,1,1, 1,1,1,1, 1,1,1,1];  // all 16th notes
    const hhOp  = [0,0,0,0, 0,0,1,0, 0,0,0,0, 0,0,1,0];  // open on "2 and", "4 and"

    for (let s = 0; s < 16; s++) {
      const t = barStart + s * stepDur + (Math.random() - 0.5) * 0.003;
      if (kick[s])       this.playKick808(t);
      if (snare[s])      this.playSnare(t, 0.24);
      if (hhOp[s])       this.playOpenHH(t, 0.072);
      else if (hhCl[s])  this.playHH(t, 0.055);
    }

    // Upward arpeggio at bar start — each chord note 40ms apart
    bar.chord.forEach((midi: number, i: number) => {
      const t = barStart + i * 0.042;
      const c = this.actx!;
      const osc  = c.createOscillator();
      const gain = c.createGain();
      const lpf  = c.createBiquadFilter();
      osc.type = 'triangle'; osc.frequency.value = mf(midi + 12); // one octave up
      lpf.type = 'lowpass'; lpf.frequency.value = 2800;
      gain.gain.setValueAtTime(0, t);
      gain.gain.linearRampToValueAtTime(0.058, t + 0.008);
      gain.gain.exponentialRampToValueAtTime(0.001, t + 0.20);
      osc.connect(gain); gain.connect(lpf); lpf.connect(this.masterGain!);
      osc.start(t); osc.stop(t + 0.24);
    });
  }

  // ── Master scheduler — dispatches by style name, not track index ─────────

  private scheduleBar(config: LofiTrackConfig, bar: TrackBar, barStart: number, beatDur: number) {
    switch (config.style) {
      case 'halfTime': this.scheduleBar0(bar, barStart, beatDur); break;
      case 'upbeat':   this.scheduleBar1(bar, barStart, beatDur); break;
      case 'ambient':  this.scheduleBar2(bar, barStart, beatDur); break;
      case 'jazz':     this.scheduleBar3(bar, barStart, beatDur); break;
      case 'driving':  this.scheduleBar4(bar, barStart, beatDur); break;
    }
  }

  private loop() {
    if (!this.playing || !this.actx) return;
    const track   = LOFI_TRACKS[this.trackIdx];
    const beatDur = 60 / track.bpm;
    const barDur  = beatDur * 4;

    const horizon = this.actx.currentTime + barDur + 0.35;
    while (this.nextBarTime < horizon) {
      const bar = track.bars[this.barIdx % track.bars.length];
      this.scheduleBar(track, bar, this.nextBarTime, beatDur);
      this.barIdx = (this.barIdx + 1) % track.bars.length;
      this.nextBarTime += barDur;
    }

    this.scheduleTimer = setTimeout(() => this.loop(), barDur * 500);
  }

  // ── Public API ────────────────────────────────────────────────────────────

  play(trackIdx: number, volume: number) {
    const c = this.boot();
    this.trackIdx    = trackIdx;
    this.playing     = true;
    this.barIdx      = 0;
    this.nextBarTime = c.currentTime + 0.10;
    this.masterGain!.gain.setValueAtTime(volume / 100, c.currentTime);
    if (this.scheduleTimer) clearTimeout(this.scheduleTimer);
    // Rain texture — enabled when the track's style is 'ambient'
    if (LOFI_TRACKS[trackIdx]?.style === 'ambient') this.startRain();
    this.loop();
  }

  stop() {
    this.playing = false;
    this.stopRain();
    if (this.scheduleTimer) { clearTimeout(this.scheduleTimer); this.scheduleTimer = null; }
    if (this.masterGain && this.actx) {
      const now = this.actx.currentTime;
      this.masterGain.gain.setValueAtTime(this.masterGain.gain.value, now);
      this.masterGain.gain.linearRampToValueAtTime(0, now + 0.6);
    }
  }

  setVolume(volume: number) {
    if (this.masterGain && this.actx) {
      this.masterGain.gain.linearRampToValueAtTime(volume / 100, this.actx.currentTime + 0.08);
    }
  }

  setTrack(trackIdx: number, volume: number) {
    if (!this.playing) return;
    this.stop();
    setTimeout(() => this.play(trackIdx, volume), 620);
  }

  isPlaying() { return this.playing; }
}

export const lofiPlayer = new LofiEngine();
